const Icon = ({ children }: { children: React.ReactNode }) => <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-5 w-5">{children}</svg>;
const Arrow = () => <Icon><path d="M5 19 19 5M8 5h11v11" strokeLinecap="round" strokeLinejoin="round" /></Icon>;
const Pin = () => <Icon><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z" /><circle cx="12" cy="10" r="2.5" /></Icon>;

const places = [
  ["Aizawl", "City views & local culture", "city"], ["Reiek", "Village stays & mountain air", "ridge"],
  ["Hmuifang", "Misty meadows & quiet trails", "meadow"], ["Vangchhia", "Ancient stones & wild hills", "valley"],
];
const stays = [
  ["Lushai Hill Cottage", "Reiek · 2 guests", "₹2,800", "stay-one", "Guest favourite"],
  ["Durtlang View House", "Aizawl · 4 guests", "₹3,600", "stay-two", "Verified home"],
  ["Thenzawl Forest Cabin", "Thenzawl · 2 guests", "₹2,400", "stay-three", "New on MizoramStay"],
];

export default function Home() {
  return <main id="top" className="site-shell overflow-hidden">
    <header className="mx-auto flex w-full max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10" aria-label="Main navigation">
      <a href="#top" className="brand-mark text-xl font-bold tracking-tight" aria-label="MizoramStay home">mizoram<span>stay</span></a>
      <nav className="hidden items-center gap-8 text-sm font-medium md:flex" aria-label="Primary"><a className="nav-link" href="#discover">Discover</a><a className="nav-link" href="#promise">How it works</a><a className="nav-link" href="#hosts">For hosts</a></nav>
      <a href="#hosts" className="rounded-full border border-[var(--line)] px-4 py-2 text-sm font-semibold transition hover:border-[var(--ink)] hover:bg-white">List your stay</a>
    </header>

    <section className="hero-section relative mx-auto max-w-7xl px-5 pb-20 pt-8 sm:px-8 lg:px-10 lg:pb-28 lg:pt-14">
      <div className="hero-copy relative z-10 max-w-3xl"><p className="eyebrow mb-5">Northeast India, slowly</p><h1 className="text-5xl font-semibold tracking-[-0.055em] sm:text-6xl lg:text-8xl">Come home to the <em className="serif font-normal italic">hills.</em></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--muted)]">Thoughtful stays, warmly hosted. Find your way into Mizoram’s living landscapes, village kitchens and unhurried mornings.</p></div>
      <div className="hero-art" aria-hidden="true"><div className="sun-disc"/><div className="cloud cloud-one"/><div className="cloud cloud-two"/><div className="mountain mountain-back"/><div className="mountain mountain-mid"/><div className="mountain mountain-front"/><div className="home-shape"><span/><i/></div><div className="tree tree-one"/><div className="tree tree-two"/><div className="tree tree-three"/></div>
      <form className="search-card relative z-20 mt-12 grid max-w-5xl gap-1 p-2 md:grid-cols-[1.4fr_1fr_1fr_auto]" aria-label="Search for stays">
        <label className="search-field"><span>Where</span><div className="flex items-center gap-2"><Pin/><input aria-label="Destination" placeholder="Try Aizawl or Reiek"/></div></label><label className="search-field"><span>When</span><button type="button" className="text-left font-medium">Add dates</button></label><label className="search-field"><span>Guests</span><button type="button" className="text-left font-medium">Add guests</button></label><button type="submit" className="search-button"><span className="hidden sm:inline">Search stays</span><Icon><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4" strokeLinecap="round"/></Icon></button>
      </form><p className="relative z-20 mt-4 text-sm text-[var(--muted)]">Local hosts · Carefully reviewed homes · Real Mizo welcome</p>
    </section>

    <section id="promise" className="border-y border-[var(--line)] bg-[var(--deep)] px-5 py-16 text-[var(--paper)] sm:px-8 lg:px-10 lg:py-20"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.9fr_2fr] lg:gap-20"><div><p className="eyebrow text-[var(--gold)]">The MizoramStay promise</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Travel with <em className="serif font-normal italic">confidence.</em></h2></div><div className="grid gap-9 sm:grid-cols-3">{[["Verified stays","Every place is checked for accuracy, safety and a real local connection."],["Hosts who care","Stay with people who know the road, the rain and where the best food is."],["Travel that gives back","More of your trip stays in Mizoram, supporting homes and communities."]].map(([title,copy],i)=><article key={title} className="border-t border-white/25 pt-5"><div className="mb-5 flex h-10 w-10 items-center justify-center rounded-full border border-white/30 text-[var(--gold)]">0{i+1}</div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/65">{copy}</p></article>)}</div></div></section>

    <section id="discover" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Find your corner</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Go where the map gets quiet.</h2></div><a href="#stays" className="link-arrow">Explore all places <Arrow/></a></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{places.map(([name,note,type])=><a href="#stays" key={name} className={`destination-card ${type}`}><div className="destination-landscape" aria-hidden="true"><span/><i/><b/></div><div className="relative"><p className="text-lg font-semibold">{name}</p><p className="mt-1 text-sm text-[var(--muted)]">{note}</p><span className="mt-5 inline-flex h-8 w-8 items-center justify-center rounded-full border border-[var(--line)]"><Arrow/></span></div></a>)}</div></section>

    <section id="stays" className="bg-[var(--sand)] px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">A few good places</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Stay awhile.</h2></div><a href="#top" className="link-arrow">See all stays <Arrow/></a></div><div className="mt-10 grid gap-6 md:grid-cols-3">{stays.map(([name,place,price,art,tag],i)=><article key={name} className="stay-card"><div className={`stay-art ${art}`} aria-label={`Illustration of ${name}`} role="img"><span/><i className="art-mountain one"/><i className="art-mountain two"/><b className="art-house"/></div><div className="p-5"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-wider text-[var(--terracotta)]">{tag}</p><span className="text-sm">★ 4.{9-i}</span></div><h3 className="mt-3 text-xl font-semibold">{name}</h3><p className="mt-1 text-sm text-[var(--muted)]">{place}</p><p className="mt-5 text-sm"><strong>{price}</strong> <span className="text-[var(--muted)]">night</span></p></div></article>)}</div></div></section>

    <section id="hosts" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="host-card relative overflow-hidden px-7 py-12 sm:px-12 lg:px-16 lg:py-16"><div className="relative z-10 max-w-xl"><p className="eyebrow text-[var(--gold)]">Open your door</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-white sm:text-5xl">Your place has a story. <em className="serif font-normal italic">Let guests hear it.</em></h2><p className="mt-5 max-w-md leading-7 text-white/70">Join a community of hosts sharing the Mizoram they know and love. It is free to list, and we are beside you from first photo to first hello.</p><a href="#top" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[var(--gold)] px-5 py-3 text-sm font-semibold text-[var(--deep)] transition hover:bg-white">Become a host <Arrow/></a></div><div className="host-hills" aria-hidden="true"><i/><b/><span/></div></div></section>
    <footer className="border-t border-[var(--line)] px-5 py-8 sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 text-sm sm:flex-row sm:items-center"><p className="brand-mark font-bold">mizoram<span>stay</span></p><p className="text-[var(--muted)]">Travel gently. Stay locally. © 2025 MizoramStay</p><div className="flex gap-5"><a className="nav-link" href="#top">Instagram</a><a className="nav-link" href="#top">Contact</a></div></div></footer>
  </main>;
}
