import Link from "next/link";
import { notFound } from "next/navigation";
import { demoProperties } from "@/features/properties/types";

type Destination = { name: string; eyebrow: string; introduction: string; bestFor: string[]; notes: string[]; nearby: string[] };
const destinations: Record<string, Destination> = {
  aizawl: { name: "Aizawl", eyebrow: "City on the ridgeline", introduction: "Aizawl is a lively hill capital where neighbourhood walks, market mornings, and long valley views can all fit into an unhurried day.", bestFor: ["City breaks", "Food and markets", "Day excursions"], notes: ["Build in time for steep lanes and viewpoints.", "Ask your host for current local transport guidance.", "Pack a light layer for cooler evenings."], nearby: ["Durtlang Hills", "Local markets", "Neighbourhood cafés"] },
  reiek: { name: "Reiek", eyebrow: "Village and valley views", introduction: "Reiek offers a quieter base in the hills, with village life, forested slopes, and room to slow down between short explorations.", bestFor: ["Scenic stays", "Gentle walks", "Quiet weekends"], notes: ["Weather can shift quickly across the hills.", "Confirm pickup options with your stay in advance.", "Respect private homes and local routines."], nearby: ["Reiek village", "Ridge walks", "Valley viewpoints"] },
  thenzawl: { name: "Thenzawl", eyebrow: "Cool air, craft, and falls", introduction: "Thenzawl is a relaxed base for travellers drawn to green surroundings, weaving traditions, and waterfall day trips.", bestFor: ["Nature breaks", "Craft discovery", "Small-group travel"], notes: ["Carry sturdy shoes for uneven paths.", "Check seasonal conditions before waterfall visits.", "Choose reusable bottles and take litter with you."], nearby: ["Vantawng Falls", "Weaving villages", "Forest roads"] },
};

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return Object.keys(destinations).map((slug) => ({ slug })); }
export default async function DestinationPage({ params }: Props) {
  const { slug } = await params;
  const destination = destinations[slug.toLowerCase()];
  if (!destination) notFound();
  const stays = demoProperties.filter((stay) => stay.destination.toLowerCase() === destination.name.toLowerCase());
  return <main className="min-h-screen bg-[var(--paper)]"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><Link className="brand-mark text-xl font-bold" href="/">mizoram<span>stay</span></Link><Link href="/stays" className="text-sm font-semibold underline underline-offset-4">Browse all stays</Link></header><section className="mx-auto max-w-7xl px-5 pb-20 pt-8 sm:px-8 lg:px-10"><div className="relative overflow-hidden rounded-[2rem] bg-[var(--sky)] px-6 py-14 sm:px-10 lg:px-16"><div className="absolute bottom-0 right-0 h-48 w-2/3 bg-[var(--forest)] opacity-80 [clip-path:polygon(0_100%,35%_16%,54%_48%,78%_0,100%_100%)]"/><div className="relative max-w-2xl"><p className="eyebrow">{destination.eyebrow}</p><h1 className="serif mt-3 text-5xl leading-none tracking-tight sm:text-6xl">Discover {destination.name}</h1><p className="mt-6 text-lg leading-8 text-[var(--muted)]">{destination.introduction}</p></div></div><div className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">At your own pace</p><h2 className="mt-2 text-3xl font-semibold">A thoughtful starting point</h2><div className="mt-6 grid gap-4 sm:grid-cols-3">{destination.bestFor.map((item) => <div className="rounded-2xl border border-[var(--line)] bg-white p-5" key={item}><p className="font-semibold">{item}</p></div>)}</div><h2 className="mt-10 text-2xl font-semibold">Nearby ideas</h2><ul className="mt-4 grid gap-3 sm:grid-cols-3">{destination.nearby.map((item) => <li className="rounded-xl bg-[var(--sand)] px-4 py-4 text-sm font-semibold" key={item}>{item}</li>)}</ul></div><aside className="rounded-3xl border border-[var(--line)] bg-white p-6"><h2 className="text-xl font-semibold">Travel with care</h2><ul className="mt-5 space-y-4">{destination.notes.map((note) => <li className="flex gap-3 text-sm leading-6 text-[var(--muted)]" key={note}><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[var(--terracotta)]"/>{note}</li>)}</ul><p className="mt-6 border-t border-[var(--line)] pt-5 text-xs leading-5 text-[var(--muted)]">These are independent travel-planning suggestions, not official or government advice. Confirm current requirements locally before travelling.</p></aside></div><section className="mt-12 rounded-3xl bg-[var(--deep)] p-6 text-white sm:p-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow !text-[var(--gold)]">Find your base</p><h2 className="serif mt-2 text-3xl">Stay a little longer in {destination.name}.</h2><p className="mt-3 max-w-xl leading-7 text-white/75">Choose a local stay, then use your host&apos;s practical knowledge to shape the details.</p></div><Link className="shrink-0 rounded-full bg-white px-5 py-3 text-sm font-bold text-[var(--deep)]" href={stays[0] ? `/stays/${stays[0].slug}` : "/stays"}>{stays[0] ? "See a stay" : "Explore stays"}</Link></div></section></section></main>;
}
