import Link from "next/link";

export const metadata = { title: "Travel guides", description: "Practical, thoughtful planning notes for a stay in Mizoram." };
const guides = [
  { category: "Before you book", title: "Choosing a stay that suits your trip", text: "Compare location, room setup, access, and host notes before you reserve.", href: "/stays" },
  { category: "Getting around", title: "Plan slower days in the hills", text: "Leave room for winding roads, changing weather, and the pleasure of an unplanned viewpoint.", href: "/destinations/aizawl" },
  { category: "Packing list", title: "What to bring for changeable weather", text: "Light layers, rain protection, comfortable shoes, and a refillable bottle are useful starting points.", href: "/destinations/reiek" },
  { category: "Good guest habits", title: "A respectful visit starts with listening", text: "Ask before photographing people or private spaces, follow your host’s guidance, and leave places as you found them.", href: "/destinations/thenzawl" },
  { category: "For families", title: "Make room for a gentler itinerary", text: "Choose one anchor activity a day and check stay amenities and access needs before booking.", href: "/stays" },
  { category: "With your host", title: "Questions worth asking before arrival", text: "Confirm directions, check-in timing, meals, connectivity, and anything you need for a comfortable stay.", href: "/booking/confirmation" },
];
export default function TravelGuidesPage() { return <main className="min-h-screen bg-[var(--paper)]"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><Link className="brand-mark text-xl font-bold" href="/">mizoram<span>stay</span></Link><Link href="/stays" className="text-sm font-semibold underline underline-offset-4">Find a stay</Link></header><section className="mx-auto max-w-7xl px-5 pb-20 pt-10 sm:px-8 lg:px-10"><div className="max-w-3xl"><p className="eyebrow">Travel planning</p><h1 className="serif mt-3 text-5xl leading-tight tracking-tight sm:text-6xl">Useful notes for an easier journey.</h1><p className="mt-5 text-lg leading-8 text-[var(--muted)]">A small collection of practical prompts for travelling well, choosing a stay, and making space for the unexpected.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{guides.map((guide, index) => <article className="group flex min-h-64 flex-col rounded-3xl border border-[var(--line)] bg-white p-6 transition hover:-translate-y-1 hover:shadow-lg" key={guide.title}><p className="eyebrow">0{index + 1} · {guide.category}</p><h2 className="mt-5 text-2xl font-semibold leading-tight">{guide.title}</h2><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{guide.text}</p><Link className="mt-auto pt-6 text-sm font-bold underline underline-offset-4" href={guide.href}>Read planning notes <span aria-hidden="true">→</span></Link></article>)}</div><section className="mt-10 grid gap-6 rounded-3xl bg-[var(--sand)] p-6 sm:p-10 lg:grid-cols-[1fr_auto]"><div><p className="eyebrow">One final reminder</p><h2 className="mt-2 text-3xl font-semibold">Check current details before you go.</h2><p className="mt-3 max-w-2xl leading-7 text-[var(--muted)]">Routes, local conditions, and entry requirements can change. These guides are general planning support, not official or government guidance; verify time-sensitive information with relevant local sources and your host.</p></div><Link className="h-fit self-end rounded-full bg-[var(--terracotta)] px-5 py-3 text-center text-sm font-bold text-white" href="/stays">Explore stays</Link></section></section></main>; }
